"""
echo "AGnews - BM"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="basic_mission" --LM="Snorkel"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="basic_mission" --LM="WMV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="basic_mission" --LM="MV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="basic_mission" --LM="DS"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="basic_mission" --LM="FS"
"""

echo "AGnews - TD"
# python3 autolfgen_integration.py --dataset="agnews" --prompt_type="task_description" --LM="Snorkel"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="task_description" --LM="WMV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="task_description" --LM="MV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="task_description" --LM="DS"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="task_description" --LM="FS"

echo "AGnews - HH"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_heuristic" --LM="Snorkel"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_heuristic" --LM="WMV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_heuristic" --LM="MV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_heuristic" --LM="DS"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_heuristic" --LM="FS"

echo "AGnews - HL"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_label_function" --LM="Snorkel"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_label_function" --LM="WMV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_label_function" --LM="MV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_label_function" --LM="DS"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="human_label_function" --LM="FS"

echo "AGnews - DE"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="data_example" --LM="Snorkel"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="data_example" --LM="WMV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="data_example" --LM="MV"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="data_example" --LM="DS"
python3 autolfgen_integration.py --dataset="agnews" --prompt_type="data_example" --LM="FS"